import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import USGSDataProvider from "../state/providers/usgsProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header className='rounded-lg bg-blue-600 p-10 m-2 text-white text-center font-bold mx-auto w-4/5'>
          Your App Title Here
        </header>

        <USGSDataProvider>{children}</USGSDataProvider>
      </body>
    </html>
  );
}
